#!/bin/bash
#
# Copyright (c) 2020 Jim Ramsay <i.am@jimramsay.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

libpaths() {
    local PYTHON=$1
    $PYTHON -c "import sys; print('\n'.join(sys.path))" | grep -e "site-packages" -e "dist-packages"
}

LIB="gi"
SYSPYTHON="/usr/bin/python3"

syspaths=$(libpaths $SYSPYTHON)
LIBPATH=
for path in $syspaths; do
    if [[ -d "$path/gi" ]]; then
        LIBPATH="$path/gi"
    fi
done
echo "Found system libpath for $LIB: $LIBPATH"

envpaths=$(libpaths "pipenv run python3")
for path in $envpaths; do
    echo "Trying to link $LIB into envpath $path"
    ln -s "$LIBPATH" "$path"
    if [[ $? == 0 ]]; then
        echo "Success"
        break
    fi
done
